module.exports = function () {
  return {
    products: [{
        id: 1,
        name: 'Sandwich',
        date: '15 May 2019',
        category: 'Food',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'An item of food consisting of two pieces of bread with a filling between them, eaten as a light meal.',
        img: '/assets/images/Sandwich.jpg',
        veg: 'green'
      },
      {
        id: 2,
        name: 'Pasta',
        date: '15 May 2019',
        category: 'Food',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'Food made from flour, water, and sometimes egg, that is cooked and usually served with a sauce. It is made in various shapes that have different names.',
        img: '/assets/images/Pasta.jpg',
        veg: 'green'
      },
      {
        id: 3,
        name: 'French Fries',
        date: '15 May 2019',
        category: 'Food',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'Long, thin pieces of potato that are fried and eaten hot.',
        img: '/assets/images/FrenchFries.jpg',
        veg: 'green'
      },
      {
        id: 4,
        name: 'Burger',
        date: '15 May 2019',
        category: 'Food',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'A flat round cake of minced potatoes mixed with other vegetables, fried or grilled and typically served in a bread roll garnished with various condiments.',
        img: '/assets/images/Burger.jpg',
        veg: 'green'
      },
      {
        id: 5,
        name: 'Pizza',
        date: '15 May 2019',
        category: 'Food',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'A dish of Italian origin, consisting of a flat round base of dough baked with a topping of tomatoes and cheese, typically with added meat, fish, or vegetables.',
        img: '/assets/images/Pizza.jpg',
        veg: 'green'
      },
      {
        id: 6,
        name: 'Coke',
        date: '15 May 2019',
        category: 'Soft Drink',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Coca-Cola',
        desc: 'A carbonated non-alcoholic drink manufactured by the Coca-Cola Company.',
        img: '/assets/images/Coke.png',
        veg: 'green'
      },
      {
        id: 7,
        name: 'Sprite',
        date: '15 May 2019',
        category: 'Soft Drink',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Coca-Cola',
        desc: 'Sprite is a colorless, caffeine-free, lemon and lime-flavored soft drink created by The Coca-Cola Company.',
        img: '/assets/images/Sprite.jpg',
        veg: 'green'
      },
      {
        id: 8,
        name: 'Mountain-Dew',
        date: '15 May 2019',
        category: 'Soft Drink',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'PepsiCo',
        desc: 'Mountain Dew is a carbonated soft drink brand produced and owned by PepsiCo',
        img: '/assets/images/MountainDew.png',
        veg: 'green'
      },
      {
        id: 9,
        name: 'Tea',
        date: '15 May 2019',
        category: 'Soft Drink',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'A hot drink made by infusing the dried crushed leaves of the tea plant in boiling water.',
        img: '/assets/images/Tea.jpeg',
        veg: 'green'
      },
      {
        id: 10,
        name: 'Coffee',
        date: '15 May 2019',
        category: 'Soft Drink',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Cooked',
        desc: 'A hot drink made from the roasted and ground seeds (coffee beans) of a tropical shrub.',
        img: '/assets/images/Coffee.jpg',
        veg: 'green'
      },
      {
        id: 11,
        name: 'Chips',
        date: '15 May 2019',
        category: 'Packed Snacks',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Packed',
        desc: 'A long rectangular piece of deep-fried potato.',
        img: '/assets/images/Chips.jpg',
        veg: 'green'
      },
      {
        id: 12,
        name: 'Nachos',
        date: '15 May 2019',
        category: 'Packed Snacks',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Doritos',
        desc: 'A dish of tortilla chips topped with melted cheese and often also with other savoury toppings.',
        img: '/assets/images/Nachos.jpg',
        veg: 'green'
      },
      {
        id: 13,
        name: 'Namkeen',
        date: '15 May 2019',
        category: 'Packed Snacks',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Haldiram',
        desc: 'A small savoury snack or dish.',
        img: '/assets/images/Namkeen.jpg',
        veg: 'green'
      },
      {
        id: 13,
        name: 'Lays',
        date: '15 May 2019',
        category: 'Packed Snacks',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Frito-Lay',
        desc: 'Potato chips varieties produced by Frito-Lay.',
        img: '/assets/images/Lays.jpg',
        veg: 'green'
      },
      {
        id: 14,
        name: 'Pringles',
        date: '15 May 2019',
        category: 'Packed Snacks',
        quantity: 100,
        inventory: 0,
        type: 'Non-Perishable',
        company: 'Pringles',
        desc: 'Brand of potato and wheat-based stackable snack chips.',
        img: '/assets/images/Pringles.jpg',
        veg: 'green'
      },
      {
        id: 16,
        name: 'Rolled Biscuits',
        date: '15 May 2019',
        category: 'Biscuits',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'Rolled biscuits are one of the most popular baking-powder leavened quick breads.',
        img: '/assets/images/RolledBiscuits.jpg',
        veg: 'green'
      },
      {
        id: 17,
        name: 'Drop Biscuits',
        date: '15 May 2019',
        category: 'Biscuits',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'Drop biscuits have more milk or other liquid added to the dough than rolled biscuits. The dough is moister and cannot be kneaded or rolled.',
        img: '/assets/images/DropBiscuits.jpg',
        veg: 'green'
      },
      {
        id: 18,
        name: 'Scones',
        date: '15 May 2019',
        category: 'Biscuits',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'Scones are sweet, rich wedge-shaped biscuits that are usually made with cream as well as butter. Scones have a tender, heavy crumb and a slightly crusty brown top. ',
        img: '/assets/images/Scones.jpg',
        veg: 'green'
      },
      {
        id: 19,
        name: 'Shortcakes',
        date: '15 May 2019',
        category: 'Biscuits',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'Shortcakes use rich biscuits or scones as a base. They are either split or served whole, topped with sweetened fruit and whipped cream or ice cream.',
        img: '/assets/images/Shortcakes.jpg',
        veg: 'green'
      },
      {
        id: 20,
        name: 'Viennese whirls',
        date: '15 May 2019',
        category: 'Biscuits',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'Viennese whirls are a sandwich biscuit made up of two shortbread biscuits held together with raspberry jam and buttercream.',
        img: '/assets/images/VienneseWhirls.jpg',
        veg: 'green'
      },
      {
        id: 21,
        name: 'Cookies',
        date: '15 May 2019',
        category: 'Bakery',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Britannia',
        desc: 'A baked or cooked food that is small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts, etc.',
        img: '/assets/images/Cookies.jpg',
        veg: 'green'
      },
      {
        id: 22,
        name: 'Cake',
        date: '15 May 2019',
        category: 'Bakery',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Britannia',
        desc: 'An item of soft sweet food made from a mixture of flour, fat, eggs, sugar, and other ingredients, baked and sometimes iced or decorated.',
        img: '/assets/images/Cake.jpg',
        veg: 'green'
      },
      {
        id: 23,
        name: 'Pastry',
        date: '15 May 2019',
        category: 'Bakery',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'A food made from a mixture of flour, fat, and water, rolledflat and either wrapped around or put over or under other foods, and then baked.',
        img: '/assets/images/Pastry.jpg',
        veg: 'green'
      },
      {
        id: 24,
        name: 'Pudding',
        date: '15 May 2019',
        category: 'Bakery',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'A cooked sweet dish served after the main course of a meal.',
        img: '/assets/images/Pudding.jpg',
        veg: 'green'
      },
      {
        id: 25,
        name: 'Chocolate Brownies',
        date: '15 May 2019',
        category: 'Bakery',
        quantity: 100,
        inventory: 0,
        type: 'Perishable',
        company: 'Baked',
        desc: 'A chocolate brownie is a square, baked, chocolate dessert. Brownies come in a variety of forms and may be either fudgy or cakey, depending on their density. They may include nuts, frosting, cream cheese, chocolate chips, or other ingredients',
        img: '/assets/images/ChocolateBrownies.jpg',
        veg: 'green'
      },
    ],
    orders: []
  }
}
